export const KDCMF_SEAL = 'https://tkctcmpkbidbhjxaghkx.supabase.co/storage/v1/object/public/public-assets/Kingdom%20Dominion%20CMF%20Seal.png'
export const BISHOP_SEAL = 'https://tkctcmpkbidbhjxaghkx.supabase.co/storage/v1/object/public/public-assets/Seal%20of%20the%20Bishop%20KDCMF%20with%20red%20background.png'
export const AES_LOGO = 'https://tkctcmpkbidbhjxaghkx.supabase.co/storage/v1/object/public/public-assets/AES%20Logo.png'
export const KDI_LOGO = 'https://tkctcmpkbidbhjxaghkx.supabase.co/storage/v1/object/public/public-assets/KDI%20Logo.png'
export const SAVE_THE_DATE_2026 = 'https://tkctcmpkbidbhjxaghkx.supabase.co/storage/v1/object/public/public-assets/Save%20The%20Date-2026.jpg'
